import React, { useMemo } from 'react';
import {
  Instagram,
  Heart,
  MessageCircle,
  ExternalLink
} from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

export interface InstagramPost {
  id: string;
  title: string;
  image: string;
  likes: number;
  comments: number;
  link: string;
  order: number;
  location?: string;
  caption?: string;
}

interface CmsInstagramData {
  title?: string;
  location?: string;
  caption?: string;
  image?: string;
  imageUrl?: string;
  link?: string;
  post_url?: string;
  postUrl?: string;
  likes?: number | string;
  comments?: number | string;
  order?: number | string;
}

const INSTAGRAM_PROFILE_URL = 'https://www.instagram.com/smart_orga/';

/**
 * Parses simple YAML frontmatter from raw Markdown files generated by Decap CMS
 */
function parseFrontmatter(raw: string): Record<string, any> {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const yamlContent = match[1];
  const result: Record<string, any> = {};

  yamlContent.split(/\r?\n/).forEach((line) => {
    const colonIdx = line.indexOf(':');
    if (colonIdx > 0) {
      const key = line.slice(0, colonIdx).trim();
      let val = line.slice(colonIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      if (val === 'true') result[key] = true;
      else if (val === 'false') result[key] = false;
      else if (!isNaN(Number(val)) && val !== '') result[key] = Number(val);
      else result[key] = val;
    }
  });

  return result;
}

/**
 * Loads Instagram posts dynamically from Decap CMS content folder (content/instagram/*.{json,md})
 */
function loadCmsInstagramPosts(): InstagramPost[] {
  const posts: InstagramPost[] = [];

  // 1. Dynamic import of all JSON files in content/instagram
  const jsonModules = import.meta.glob<Record<string, any>>('/content/instagram/*.json', { eager: true });
  Object.entries(jsonModules).forEach(([path, mod], idx) => {
    const data = ((mod as { default?: CmsInstagramData }).default || mod) as CmsInstagramData;
    if (!data) return;

    const fileSlug = path.split('/').pop()?.replace(/\.json$/, '') || `post-${idx}`;
    const title = data.title || data.location || data.caption || 'Instant Smart Orga';
    const image = data.image || data.imageUrl || '';
    const link = data.link || data.post_url || data.postUrl || INSTAGRAM_PROFILE_URL;
    const likes = typeof data.likes === 'number' ? data.likes : Number(data.likes) || 0;
    const comments = typeof data.comments === 'number' ? data.comments : Number(data.comments) || 0;
    const order = typeof data.order === 'number' ? data.order : Number(data.order) || idx + 1;

    posts.push({
      id: fileSlug,
      title,
      image,
      likes,
      comments,
      link,
      order,
      location: data.location || title,
      caption: data.caption || title,
    });
  });

  // 2. Dynamic import of any Markdown files in content/instagram
  const mdModules = import.meta.glob<string>('/content/instagram/*.md', { eager: true, query: '?raw', import: 'default' });
  Object.entries(mdModules).forEach(([path, rawContent], idx) => {
    const data = parseFrontmatter(rawContent) as CmsInstagramData;
    if (!data) return;

    const fileSlug = path.split('/').pop()?.replace(/\.md$/, '') || `md-post-${idx}`;
    const title = data.title || data.location || data.caption || 'Instant Smart Orga';
    const image = data.image || data.imageUrl || '';
    const link = data.link || data.post_url || data.postUrl || INSTAGRAM_PROFILE_URL;
    const likes = typeof data.likes === 'number' ? data.likes : Number(data.likes) || 0;
    const comments = typeof data.comments === 'number' ? data.comments : Number(data.comments) || 0;
    const order = typeof data.order === 'number' ? data.order : Number(data.order) || idx + 100;

    posts.push({
      id: fileSlug,
      title,
      image,
      likes,
      comments,
      link,
      order,
      location: data.location || title,
      caption: data.caption || title,
    });
  });

  // Sort strictly by the order defined in Decap CMS
  return posts.sort((a, b) => a.order - b.order);
}

export const InstagramGallery: React.FC = () => {
  const { t } = useLanguage();

  // Dynamically loaded posts from Decap CMS
  const posts = useMemo<InstagramPost[]>(() => {
    return loadCmsInstagramPosts();
  }, []);

  return (
    <section id="instagram-gallery-section" className="py-16 sm:py-24 bg-white border-b border-slate-100 scroll-mt-20 overflow-hidden relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-3">
          <div className="flex items-center justify-center">
            <a
              id="instagram-profile-badge-link"
              href={INSTAGRAM_PROFILE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-bold tracking-widest text-blue-600 hover:text-pink-600 uppercase transition-colors group cursor-pointer"
            >
              <Instagram className="w-4 h-4 text-pink-500" />
              <span>{t.instaBadge || "@SMART_ORGA • INSTAGRAM GALLERY"}</span>
              <ExternalLink className="w-3 h-3 opacity-60 group-hover:opacity-100 transition-opacity" />
            </a>
          </div>

          <h2 id="instagram-gallery-heading" className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-slate-900 tracking-tight">
            {t.instaTitle || "Instants de Bonheur Capturés"}
          </h2>
          <p className="text-sm sm:text-base text-slate-600 leading-relaxed max-w-2xl mx-auto">
            {t.instaSubtitle || "Suivez nos aventures régulières en temps réel sur les réseaux sociaux."}
          </p>
        </div>

        {/* Gallery Grid rendered dynamically from Decap CMS */}
        <div id="instagram-posts-grid" className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 sm:gap-4">
          {posts.map((post) => (
            <a
              key={post.id}
              id={`instagram-post-card-${post.id}`}
              href={post.link || INSTAGRAM_PROFILE_URL}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`${post.title} - ${post.likes} j'aime`}
              className="group relative aspect-square rounded-2xl overflow-hidden bg-slate-100 border border-slate-200/80 shadow-xs hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 block cursor-pointer"
            >
              {/* Photo injectée depuis le champ image du CMS */}
              <img
                src={post.image}
                alt={post.title}
                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500 ease-out"
                loading="lazy"
                referrerPolicy="no-referrer"
              />

              {/* Top Instagram badge */}
              <div className="absolute top-2.5 right-2.5 z-10 w-7 h-7 rounded-full bg-black/40 backdrop-blur-md text-white flex items-center justify-center opacity-80 group-hover:opacity-0 transition-opacity">
                <Instagram className="w-3.5 h-3.5" />
              </div>

              {/* Overlay on hover avec injection de title, caption, likes, comments */}
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-slate-900/60 to-transparent opacity-0 group-hover:opacity-100 transition-all duration-300 flex flex-col justify-between p-3.5 sm:p-4 text-white">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-pink-300 bg-pink-500/20 px-2 py-0.5 rounded-full backdrop-blur-xs line-clamp-1">
                    {post.title}
                  </span>
                  <Instagram className="w-4 h-4 text-pink-400 shrink-0 ml-1" />
                </div>

                <div className="space-y-2">
                  <p className="text-xs text-slate-100 line-clamp-2 leading-snug font-medium">
                    {post.caption || post.title}
                  </p>

                  <div className="flex items-center justify-between text-xs text-white/90 pt-1.5 border-t border-white/10 font-semibold">
                    <span className="flex items-center gap-1 text-pink-300">
                      <Heart className="w-3.5 h-3.5 fill-current" />
                      {post.likes}
                    </span>
                    <span className="flex items-center gap-1 text-slate-200">
                      <MessageCircle className="w-3.5 h-3.5 fill-current" />
                      {post.comments}
                    </span>
                  </div>
                </div>
              </div>
            </a>
          ))}
        </div>

        {/* Action Button */}
        <div className="flex items-center justify-center pt-2">
          <a
            id="instagram-follow-cta-btn"
            href={INSTAGRAM_PROFILE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2.5 px-8 py-3.5 rounded-full bg-gradient-to-r from-purple-600 via-pink-600 to-amber-500 hover:from-purple-700 hover:via-pink-700 hover:to-amber-600 text-white font-bold text-sm sm:text-base shadow-lg shadow-pink-500/25 hover:shadow-xl hover:shadow-pink-500/35 transition-all duration-300 hover:scale-105 active:scale-95 cursor-pointer"
          >
            <Instagram className="w-5 h-5 text-white" />
            <span>{t.instaFollowBtn || "Suivez-nous sur Instagram @smart_orga"}</span>
          </a>
        </div>

      </div>
    </section>
  );
};
